---
title: "Lightgbm"
author: "Amin Yakubu"
date: "2/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(Matrix)
library(dplyr)
library(MLmetrics)
library(lightgbm)
library(tidyverse)
```

```{r}
sntdr_train = read_csv("./data/train.csv")
sntdr_test = read_csv("./data/test.csv")
```

Creating a matrix and partitioning my data into train and testing

```{r}
X = sntdr_train %>% select(-ID_code, -target) %>% data.matrix()
y = sntdr_train$target

set.seed(25)
train = sample(1:nrow(X), nrow(X)/4)
test = (-train)

X.train = X[train,]
y.train = y[train]

X.test = X[test,]
y.test = y[test]
```

```{r}
dtrain <- lgb.Dataset(data = X.train,
                      label = y.train,
                      free_raw_data = FALSE)

dtest <- lgb.Dataset.create.valid(dtrain, data = X.test, label = y.test)
```

Using validation set 

```{r}
valids <- list(train = dtrain, test = dtest)
```

Searching for the best parameters 

```{r}
grid_search <- expand.grid(max_depth = c(12, 14),
                           min_data_in_leaf = c(10, 11),
                           min_sum_hessian_in_leaf = c(exp(seq(-6, 7, length = 2))),
                           feature_fraction = c(0.05, 1.0),
                           bagging_fraction = c(0.05, 1.0),
                           bagging_freq = c(5, 10),
                           lambda_l1 = c(0.2, 4.972),
                           lambda_l2 = c(0.2, 2.276),
                           min_gain_to_split = c(0.2, 0.65),
                           max_bin = c(110, 119),
                           learning_rate = c(0.02))


```

```{r}
model <- list()
perf <- numeric(nrow(grid_search))

for (i in 1:nrow(grid_search)) {
  model[[i]] <- lgb.train(list(objective = "binary",
                          metric = "auc",
                          max_depth = grid_search[i, "max_depth"],
                          min_data_in_leaf = grid_search[i,"min_data_in_leaf"],
                          min_sum_hessian_in_leaf = grid_search[i, "min_sum_hessian_in_leaf"],
                          feature_fraction =  grid_search[i, "feature_fraction"],
                          bagging_fraction =  grid_search[i, "bagging_fraction"],
                          bagging_freq =  grid_search[i, "bagging_freq"],
                          lambda_l1 =  grid_search[i, "lambda_l1"],
                          lambda_l2 =  grid_search[i, "lambda_l2"],
                          min_gain_to_split =  grid_search[i, "min_gain_to_split"],
                          max_bin = grid_search[i, 'max_bin'],
                          learning_rate = grid_search[i, 'learning_rate'],
                          num_leaves = 10,
                          boosting_type = 'gbdt',
                          is_unbalance = TRUE,
                          boost_from_average = FALSE),
                          
                          dtrain,
                          nrounds = 100,
                          valids,
                          #min_data = 1,
                          early_stopping_rounds = 50)
  
  perf[i] <- min(rbindlist(model[[i]]$record_evals$test$auc))
}

```

Grid Search

```{r}
# grid_search
cat("Model ", which.max(perf), " is highest: ", max(perf), sep = "","\n")
print(grid_search[which.min(perf), ])
```

Best
```{r}
best.grid = list(objective = "binary",
                          metric = "auc",
                          max_depth = 13,
                          min_data_in_leaf = 10,
                          min_sum_hessian_in_leaf = 10.633,
                          feature_fraction =  1,
                          bagging_fraction =  0.05,
                          bagging_freq =  5,
                          lambda_l1 =  0.2,
                          lambda_l2 =  0.2,
                          min_gain_to_split =  0.2,
                          max_bin = 110,
                          learning_rate = 0.02,
                          num_leaves = 30,
                          boosting_type = 'gbdt',
                          is_unbalance = TRUE,
                          boost_from_average = FALSE)
```


Setting parameters 

```{r}
lgb.grid = list(objective = "binary",
                num_leaves = 10,
                metric = "auc",
                min_sum_hessian_in_leaf = 0.00245,
                feature_fraction = 0.05,
                bagging_fraction = 1.0,
                bagging_freq = 5,
                max_bin = 119,
                lambda_l1 = 4.972,
                lambda_l2 = 2.276,
                min_data_in_bin = 100,
                min_gain_to_split = 0.65,
                min_data_in_leaf = 11,
                is_unbalance = TRUE,
                boost_from_average = FALSE,
                boosting_type = 'dart',
                max_depth = 14,
                save_binary = TRUE,
                learning_rate = 0.009)
```

```{r}
print("Train lightgbm using lgb.train with valids")
set.seed(28)
bst <- lgb.train(params = best.grid, 
                 data = dtrain,
                 nrounds = 1000,
                 valids = valids)

best.iter = bst$best_iter
best.iter
```


```{r}
lgb.model.cv = lgb.cv(params = lgb.grid, data = dtrain, 
                    num_threads = 2, nrounds = 10, early_stopping_rounds = 50,
                   eval_freq = 20, eval = 'auc', verbose = 1,
                    stratified = TRUE)

cv.best.iter = lgb.model.cv$best_iter
cv.best.iter

```

# Prediction

```{r}
pred <- predict(bst, X.test, num_iteration = best.iter)

err <- mean(as.numeric(pred > 0.5) != y.test)
print(paste("test-error=", err))
```

Submission

```{r}
test_matrix = sntdr_test %>% select(-ID_code) %>% data.matrix()

snt_pred <- predict(bst, test_matrix, num_iteration = best.iter)
submission = tibble(ID_code = sntdr_test$ID_code,
                    target = snt_pred)

write_csv(submission, path = "./data/final_submission-R.csv")
```

